package initcmd

import (
	"os"
	"path/filepath"
)

func initAgentTemplateFiles(templateType string, agent string) (map[string]string, error) {
	switch agent {
	case "", agentCodex:
		agents, err := readAgentTemplate("AGENTS.md")
		if err != nil {
			agents = codexAgentsFallback(templateType)
		}
		return map[string]string{"AGENTS.md": agents}, nil
	default:
		return nil, nil
	}
}

func readAgentTemplate(name string) (string, error) {
	for _, dir := range agentTemplateSearchDirs() {
		data, err := os.ReadFile(filepath.Join(dir, "template", "agent", "codex", name))
		if err == nil {
			return string(data), nil
		}
		if err != nil && !os.IsNotExist(err) {
			return "", err
		}
	}
	return "", os.ErrNotExist
}

func agentTemplateSearchDirs() []string {
	var dirs []string
	if cwd, err := os.Getwd(); err == nil {
		for dir := cwd; ; dir = filepath.Dir(dir) {
			dirs = append(dirs, dir)
			next := filepath.Dir(dir)
			if next == dir {
				break
			}
		}
	}
	return dirs
}

func codexAgentsFallback(templateType string) string {
	dirs := topLevelDirectories(templateType)
	text := `# AGENTS.md

This repository is generated by Nucleus. Keep changes contract-first, manifest-first, and easy to verify.

## Communication

- Communicate with the project owner in their preferred language.
- Keep public code comments, exported API docs, README files, and commit messages in clear English unless the file already uses another language.

## Change Loop

- Inspect service facts with ` + "`nucleus describe --dir . --json`" + ` before editing behavior.
- Plan safe edits with ` + "`nucleus plan --dir . --task \"<task>\"`" + ` before broad changes.
- Regenerate contract artifacts with ` + "`nucleus gen --dir .`" + ` after contract changes.
- Before handoff, run ` + "`nucleus verify --dir . --json`" + `.

## Top-Level Directories
`
	if len(dirs) == 0 {
		return text + "\nNo top-level directories are generated for this template.\n"
	}
	for _, dir := range dirs {
		text += "\n- `" + dir + "`"
	}
	return text + "\n"
}

func topLevelDirectories(templateType string) []string {
	switch templateType {
	case templateService:
		return []string{"api", "cmd", "configs", "contract", "deploy", "docs", "internal", "test"}
	case templateWorker:
		return []string{"cmd", "internal"}
	default:
		return nil
	}
}
